### PR TITLE
fix status update loop

### LINKED ISSUE #74: controller_bestie is getting inside a loop.
During our last tests of bestie deployment into a Kind instance, we noticed that Bestie Controller is getting inside a loop till the pods get Running. 

I've attached an image to help with the clarification.
Screenshot 2022-04-20 at 17 17 21

### PR DESCRIPTION
**Pull request by skattoju**
fixes #74

### CODE REVIEW

File: controllers/bestie_controller.go [hunk 1]
```diff
@@ -180,14 +180,14 @@ func (r *BestieReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctr
...
-	appVersion := r.reportappversion(bestie)
+	appVersion := r.getDeployedBestieVersion(ctx, bestie)
 	if !reflect.DeepEqual(appVersion, bestie.Status.AppVersion) {
 		bestie.Status.AppVersion = appVersion
 		log.Info("update app version status")
 		err := r.Status().Update(ctx, bestie)
 		if err != nil {
 			log.Error(err, "Failed to update app-version status")
-			return ctrl.Result{Requeue: true}, err
+			return ctrl.Result{}, err
```
Comment (rocrisp) [inline controllers/bestie_controller.go:190]: I'm not sure but wondering if both statements result in requeue. We have many instances of ctrl.Result{Requeue: true}, err. Perhaps we should change them to ctrl.Result{}, err

**Review by rocrisp — APPROVED** [review]
